### ISSUE TITLE
Problem with Log Pol Tens formalism intensity transformation ? 

### ISSUE THREAD

**Issue by giuspugl** [galsci/pysm#109]
Recently, an issue has been raised  on the transformation of the intensity component within the Log Pol tens formalism . I address it here

![Screen Shot 2022-02-15 at 6 21 06 PM](https://user-images.githubusercontent.com/8957029/154115158-45c55223-0e63-4111-a801-5bb1de9d761d.png)
below the maps how they look like 
![image](https://user-images.githubusercontent.com/8957029/154115714-1d69e053-3c9e-41d5-8d56-0d56920d2ea5.png)

Finally I asserted that : 
- `E[i'] = E[i] +b`:  True up to a relative tolerance of `1e-7`
-   `Var[i' ] =Var[i]` :  True up to a relative tolerance of `1e-4` 
- `Cl^i'i' = Cl^ii ` : True up to a rel. tol of `1e-5` 

i would  conclude that this issue shouldn't be worrisome for time being. what do you think ?

**Comment by delabrou** [comment]
I agree with all of this, the only issue is if the generation of the small scales depends locally on the total i (or i').
Indeed, typically, when one injects small scales, those are weighted by the local total dust emission level, and an offset in the map changes this. Unless you weight the generation of small scales with some different weighting, or you do some re-scaling later on, there should be a difference. We don't see anything in full-sky maps. Just to check, do you think you could show the original map, the small scales as generated (using the same seed), and the sum in two cases: when your original I and P maps are in uK_RJ, and when they are in K_RJ, specifically at the North Galactic pole, for a gnomonic projection?

**Comment by giuspugl** [comment]
Below the plot as @delabrou prescribed , don't see any difference apart from the fact that maps have different units... 

![image](https://user-images.githubusercontent.com/8957029/154241660-a820a8a7-6723-4771-b0bb-cf9e37e46465.png)
