### ISSUE TITLE
Porting WebSky extragalactic models to PySM 3

### ISSUE THREAD

**Issue by zonca** [galsci/pysm#120]
Currently the WebSky models are included in the `so_pysm_models` package:

https://so-pysm-models.readthedocs.io/en/latest/models.html#websky

The package is already based on PySM 3, so it should not be too difficult to move the functionality in PySM 3 proper.

However, it would be useful to first check if there is any update in WebSky itself, like maps from new simulations, or maps at resolution higher than N_side 4096.

@marcelo-alvarez has there been any update? or is there an update coming soon we should wait for?

/cc @giuspugl @brandonshensley @seclark

**Comment by zonca** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Websky to PySM 3](https://trello.com/c/rfygWOuQ/330-websky-to-pysm-3)

**Comment by marcelo-alvarez** [comment]
@zonca yes there should be an update coming soon, which @xzackli is coordinating / running. There should be the addition of radio sources, update of tSZ and CIB, and likely N_side of 8192.

**Comment by zonca** [comment]
@xzackli do you have an estimate of when the new websky will be available?

**Comment by xzackli** [comment]
@zonca We have new maps, and I"d like to set a target of Wednesday, August 24. Most of it is on disk at NERSC -- I briefly looked into writing up a pysm PR, do you have suggestions?

**Comment by zonca** [comment]
@xzackli we should mostly just port from `so_pysm_models`, adapting the code for  the new maps:

https://github.com/simonsobs/so_pysm_models/blob/master/so_pysm_models/extragalactic.py

also the maps should be in the pysm repository at NERSC:

    /global/project/projectdirs/cmb/www/pysm-data

**Comment by xzackli** [comment]
Seems sensible, looking at this now.

**Comment by xzackli** [comment]
@zonca a quick clarifying question: of course I don't have write permission to `/global/project/projectdirs/cmb/www/pysm-data`, should I just direct you to a location in scratch for you to copy over?

**Comment by zonca** [comment]
> @zonca a quick clarifying question: of course I don't have write permission to `/global/project/projectdirs/cmb/www/pysm-data`, should I just direct you to a location in scratch for you to copy over?

yes, right

**Comment by zonca** [comment]
@xzackli any update on this?

**Comment by giuspugl** [comment]
we have released  IQU maps of Radio sources painted onto Websky halos, [here](https://portal.nersc.gov/project/sobs/users/Radio_WebSky/matched_maps/) 
I would say that we can employ the approach we have previously used for CIB, i.e. interpolating maps at different frequencies , see https://so-pysm-models.readthedocs.io/en/latest/models.html#websky. 
Actually, we can allow a finer interpolation as there're ~40 maps in the range from 18 - 900 GHz all at `nside= 4096` reso. 

as we 're supposed to run several simulations for SO and Litebird asap.  How does that sound ?

**Comment by zonca** [comment]
sure @giuspugl, https://pysm3.readthedocs.io/en/latest/api/pysm3.InterpolatingComponent.html#pysm3.InterpolatingComponent is already in PySM 3.

Does this work use the new Websky release? Do newer CIB maps are available yet?

**Comment by xzackli** [comment]
We have CIB frequency maps at 
```
/global/cscratch1/sd/xzackli/cib_sources/
```
and radio maps in the directory Giuseppe listed. I'm still porting over the old pysm code to PySM3 by inheriting from the InterpolatingComponent, but I was worried about validating these CIB maps.

**Comment by zonca** [comment]
thanks @xzackli, the so-pysm-models code was already based on the PySM3 interpolating component, so changes should be minor.

**Comment by giuspugl** [comment]
@xzackli  What are the differences of the _ new CIB maps_ you're validating,wrt the ones employed   [here](https://so-pysm-models.readthedocs.io/en/latest/models.html#websky), which i believe come from WEbsky Stein et al.2020 ? 

> Does this work use the new Websky release?


@zonca  ain't sure what you mean here by `new release`, yes they used the _relatively_ recent Websky halo distribution from Stein et al.2020  . 
To my knowledge there is just one halo light-cone produced by websky abd we painted clusters, IR and radio galaxies on top of those haloes .

**Comment by giuspugl** [comment]
> I believe behave a bit better in terms of redshift evolution

Thanks @xzackli  ! I checked the redshift evolution by including the new normalization and it left kinda the same the redshift evolution, It's the Shang et al. 2012 prescription that is mostly affecting that..

**Comment by zonca** [comment]
ok, thanks @xzackli so I'll wait for a pull request, I can then also copy all the input data to the `pysm-data` folder at NERSC.

**Comment by zonca** [comment]
see #129
