### ISSUE TITLE
the GNILC large-scale template used in the PySM: unires or varres?

### ISSUE THREAD

**Issue by yaojian95** [galsci/pysm#147]
Hi Andrea, 

I'm calculating the full-sky power spectra of map from last November `/global/cfs/cdirs/cmb/www/pysm-data/dust_gnilc/![image](https://user-images.githubusercontent.com/14847517/216408071-033685cd-e921-4c59-b6f8-698b53ddbe99.png)` and it's shown in the plot (ignore the titles)

![image](https://user-images.githubusercontent.com/14847517/216403869-87122448-4b8e-42ff-b9ff-887980e0028f.png)

and also this map but transformed into `small iqu` quantities then calculated the full-sky power spectra
![image](https://user-images.githubusercontent.com/14847517/216404489-4ba76e0e-a616-4dce-92a7-a485cb62d6ad.png)

Then I also use the latest map from Giuseppe `/global/cscratch1/sd/giuspugl/cmbs4/pysm_validation/dust_gnilc_varres_pysm_circles_uKcmb.fits` to calculate the full-sky power spectra
![image](https://user-images.githubusercontent.com/14847517/216403781-b880f8be-9259-4518-8f2f-1723f0c61859.png)

also transformed into `small iqu` quantities
![image](https://user-images.githubusercontent.com/14847517/216405424-fd53a09d-1b2c-4a0b-92b6-458b520eaf5e.png)

From what I know, besides the modulation to the small scales, there should not be other differences between the `gnilc_dust_template_nside2048.fits` and `dust_gnilc_varres_pysm_circles_uKcmb.fits`. 
But the power spectra from `gnilc_dust_template_nside2048.fits` seems to show that this map is based on `GNILC-unires` large-scale templates, which can be shown if we have a look at the power spectra the Peppe had in his slides:

![image](https://user-images.githubusercontent.com/14847517/216406858-9b0f03c1-e00a-40f9-9879-551967ae597e.png)
![image](https://user-images.githubusercontent.com/14847517/216406924-e5caad8f-4e8e-4633-9cb9-2705b2d3bd2f.png)

Can you check that if you use `varres` or `unires` large-scale template to generate the maps?

**Comment by zonca** [comment]
see https://pysm3.readthedocs.io/en/latest/preprocess-templates/small_scale_dust_pysm3.html

cell 11 and below.

For temperature we are using a custom map at 21.8’, for polarization we were supposed to use `varres`.

However, there is a bug in cell 13:

```
    !wget -O $dust_varresP http://pla.esac.esa.int/pla/aio/product-action?MAP.MAP_ID=COM_CompMap_IQU-thermaldust-gnilc-unires_2048_R3.00.fits
```

it looks like it is downloading `unires` even for the `varres` case.
Thank you very much for catching this bug, I'll make sure I fix it when I regenerate the templates with the new small scales.

**Comment by zonca** [comment]
This fix is included in https://github.com/galsci/pysm/pull/150
