### ISSUE TITLE
Synchrotron beta with local-spectra modulation

### ISSUE THREAD

**Issue by zonca** [galsci/pysm#151]
This is related to #148.

I am applying the same modulation generated for the Synchrotron templates also for the synchrotron spectral index.

![image](https://user-images.githubusercontent.com/383090/219174801-5b9eb26a-bd9f-4e82-a3c8-c04549fe3214.png)

If I disable the modulation I get:
![image](https://user-images.githubusercontent.com/383090/219168167-04a07b48-2277-431f-811b-fb07c4465650.png)

The same plot for the latest beta release, from https://pysm3.readthedocs.io/en/latest/preprocess-templates/synchrotron_beta.html:

![image](https://user-images.githubusercontent.com/383090/219168780-8ccd7bf6-0358-48d9-8795-288e7a4d0c72.png)

The modulation map itself is between a factor of 2 and a factor of 3, shouldn't it have a mean of  1?:

![image](https://user-images.githubusercontent.com/383090/219174961-ef5561a2-9f65-4a1e-83b0-bb1489e560f2.png)

@giuspugl @brandonshensley @seclark should I just normalize it?
However if I normalize it for beta should I also normalize it for the templates?

**Comment by zonca** [comment]
The synchrotron beta notebook: https://gist.github.com/7d60503160fa512987474707f7006853
The synchrotron templates notebook: https://github.com/galsci/pysm/blob/9db4fcb4dcb04f411b6f552501f45a0cb7af78ef/docs/preprocess-templates/synchrotron_template_logpoltens.ipynb

**Comment by zonca** [comment]
The GNILC temperature modulation for comparison:
![image](https://user-images.githubusercontent.com/383090/219176845-de76e8df-7fed-4557-8b51-193243f72475.png)

**Comment by zonca** [comment]
also @NicolettaK @delabrou

**Comment by giuspugl** [comment]
Hi @zonca , 
i was expecting this to happen! I wouldn't touch the modulation map of Beta_s as this uses large scale templates that are derived from the old s1 + small scales fitted from SPASS data. If you agree i'd use the old modulation template of the previous beta release. That is derived from the large scale  of the intensity template . What do you and the others  think ?

**Comment by zonca** [comment]
ok @giuspugl, implemented in https://github.com/galsci/pysm/pull/152
