### ISSUE TITLE
PySM v3.4b6 synchrotron models s4, s5 and s7 validation

### ISSUE THREAD

**Issue by 1cosmologist** [galsci/pysm#153]
I did a validation study of the s4, s5 and s7 synchrotron models in PySM v3.4b6 by comparing bandpass integrated LFI 30 GHz and WMAP K band synchrotron simulations with observations. 

_Bandpasses used:_
LFI RIMO 30GHz average bandpass, WMAP 9yr bandpass frequency responses (K11, K12)

_Observations used:_ 
NPIPE (PR4) map full mission and splits A/B at NSIDE=1024, and WMAP 9yr K band maap at NSIDE=512. 
SMICA 2018 (PR3) CMB map to remove the CMB at map level (for some comparisons). 
Planck full EE power spectrum for removing CMB EE power contribution to LFI 30 GHz data. 
Planck polarized point source mask for 30 GHz. 

_Power spectra comparison:_
The IQU maps are masked with the apodized polarized point source mask. This masked map is used to obtain E and B mode maps. I mask the E/B maps with apodized 70%, 60% or 50% sky fraction masks devised based on brightness of the LFI 30 GHz polarized intensity maps. I compute power spectrum with `anafast` and divide by the fsky. For actual LFI/WMAP data we also correct for the CMB contribution to the power. 

Note: The power spectra for both the data and the simulations are processed with the same pipeline.

Here is the result for 70% sky for LFI x WMAP case. 
![image](https://user-images.githubusercontent.com/11816582/220782804-4b97eac7-344a-49c3-874c-08f49b2a280d.png)
![image](https://user-images.githubusercontent.com/11816582/220782835-0c7eb936-35aa-42af-bbe1-76b439ce5373.png)

A summary of the results can be found in the slides linked [here](https://docs.google.com/presentation/d/1Jx_dkUx-R_HJv3M575d3JuNuj6N_S5mIF4MgxSTnLtQ/edit?usp=sharing).
The jupyter notebook used in this validation study can be found [here](https://github.com/1cosmologist/code_shares/blob/main/pysm3.4.0.b6_validation_clean.ipynb)

**Comment by giuspugl** [comment]
thanks a lot @1cosmologist for doing this test. 

>  I compute power spectrum with anafast and divide by the fsky. For actual LFI/WMAP data we also correct for the CMB contribution to the power.

@zonca and I actually  estimated the power spectra with namaster to correct to mask leakage from the _Planck_ `GAL0*` masks. Your masks slightly differ from ours and this represents a valuable test to further validate the maps. Do you mind to run namaster and see how the spectra look like ? (you can find the routines in the linked notebooks in the pysm doc, see e.g. https://pysm3.readthedocs.io/en/latest/preprocess-templates/small_scale_dust_pysm3.html .

**Comment by brandonshensley** [comment]
@1cosmologist: thanks for looking into this. However, I'm having a hard time following your notebook. Could you please use PySM directly to make maps? Currently you write:

`synch_template, header = hp.read_map('../data/synch_template_nside2048.fits', field=None, h=True)`

But this is not reproducible and your maps do _not_ look like the current PySM maps. Let me know if you need help generating full sky maps at the desired NSIDE using PySM directly. Thanks.

**Comment by 1cosmologist** [comment]
@brandonshensley The s4, s5, s7 maps are produced with PySM directly. These are produced by codes in cells 5 and 9. Because they looked bit strange, we actually checked the synchrotron template being used in the models to be sure that we are not producing it. All results are computed with maps produced in cells 5 and 9. They were saved and read for subsequent runs. Let me know if I made any mistake with the code to produce the maps. Thanks for going through the code. I can update the notebook with more comments if it's too messy.

**Comment by seclark** [comment]
A simplified version of this notebook with more comments and just the "minimum working example" version of the problem here would be immensely helpful. Thanks!

**Comment by brandonshensley** [comment]
Agreed. Even just my 30 GHz intensity map (below) looks very different than those plotted in the notebook. 
![image](https://user-images.githubusercontent.com/16107367/221240268-6ad8920d-6d3a-4c62-ac92-bd6605c08c3e.png)

**Comment by brandonshensley** [comment]
Ok folks, hang tight, it looks like there might be a dependency issue where the same PySM version is yielding different output... @NicolettaK and I ran the same code, she got plots that looked like @1cosmologist's, I got things that looked more as expected. Maybe healpy version? I am using 1.16.2.

**Comment by brandonshensley** [comment]
Here is my [notebook](https://gist.github.com/brandonshensley/5a0c651f19853bfa534bb17bf0bceb07), where the synchrotron model looks to be behaving as expected.

**Comment by NicolettaK** [comment]
And [this](https://gist.github.com/NicolettaK/b00d3bef1f9f5116fe53c32d3c2eea1b) is mine. I downloaded the file `synch_template_nside2048.fits` from https://portal.nersc.gov/project/cmb/pysm-data/synch/

**Comment by brandonshensley** [comment]
@zonca , can you take a look at Nicoletta's and my notebooks to see if you have an idea of what is going on? Thanks!

**Comment by zonca** [comment]
> @zonca , can you take a look at Nicoletta's and my notebooks to see if you have an idea of what is going on? Thanks!

yes, sure

**Comment by 1cosmologist** [comment]
@brandonshensley @NicolettaK [Here](https://github.com/1cosmologist/code_shares/blob/main/pysm_v3.4b6_map-compare.ipynb) is a simplified notebook computing synchrotron maps at `NSIDE=1024` with and without bandpass integration for LFI 30 GHz. Both maps look like my maps from previous notebook. 

![image](https://user-images.githubusercontent.com/11816582/221278787-9cd5a4e7-086b-4322-a6f5-8797dfb56e1b.png)
![image](https://user-images.githubusercontent.com/11816582/221278853-41ba0c23-4d5f-401f-9467-ce0e80a19045.png)

I have also shown the versions of the main packages used in the notebook, in case it is a dependency issue. Let us first agree if these maps look like what we should get before I compare with data.

**Comment by zonca** [comment]
@brandonshensley I think you might have the template for `beta4` cached on your machine. Try:

    rm -r ~/.astropy/cache

**Comment by brandonshensley** [comment]
> 

Thanks, that "fixed" it!

**Comment by zonca** [comment]
the bug is related to https://github.com/galsci/pysm/issues/151:

the modulation map for the temperature of synchrotron is between 2 and 3, however, in the notebook that generates the templates for `beta6`, it is normalized on the fly. Also the polarization one has some tweaking on the fly. See [cell 59 of the relevant notebook](https://gist.github.com/giuspugl/b597bb26e41e7064aebaf67fda8ae251#file-expansion_synch_pysm3-ipynb).
So the version I saved and used to generate the templates is unnormalized and boosts the injected small scales abnormally.

I didn't catch the bug because I was rushing and completely forgot to compare my outputs to @giuspugl 's as I did for dust in https://github.com/galsci/pysm/issues/148.

Thanks @1cosmologist for pointing out the problem.

Now the matter is, do we have anyone volunteering to tell Julian?!

**Comment by zonca** [comment]
I'll:

- [ ] fix the bug
- [ ] regenerate all the templates for synchrotron
- [ ] compare with @giuspugl's
- [ ] release beta7
- [ ] check the impact on CMB-S4 simulations

**Comment by seclark** [comment]
Thank you very much @zonca ! And @1cosmologist thank you for finding this: I hope you can run the corrected maps through your pipeline as additional validation.

**Comment by zonca** [comment]
bug fix in https://github.com/galsci/pysm/pull/154

**Comment by zonca** [comment]
Here is the plot that shows better the issue in beta6, i.e. the excess of small scales (from [notebook](https://gist.github.com/4181717ef2d7d02a8461d9ff45d6646a):

![image](https://user-images.githubusercontent.com/383090/221373194-06dcd524-2016-45ee-ab18-e106b6e2e466.png)

This is the same for the upcoming beta7, [notebook](https://gist.github.com/3239bc4a34f9705148f715c7b1d56eba):

![image](https://user-images.githubusercontent.com/383090/221373531-eb401461-c997-40fc-977d-8c2b249ed168.png)

**Comment by zonca** [comment]
ok, I regenerated the templates after fixing the bug.
Now I am using a date in the filename of the templates, so the caching issue @brandonshensley experienced shouldn't happen anymore.
I changed the location of the old templates, so that people do not use them by mistake.
At this point `beta6` should not work anymore, on purpose.

I have released `3.4.0b7`. @1cosmologist can you please rerun your checks?
In the meantime I am rerunning the CMB-S4 map based simulations affected by this issue.

**Comment by 1cosmologist** [comment]
The beta 7 maps look a lot better:
![image](https://user-images.githubusercontent.com/11816582/221378111-85df77bb-da5f-4400-89fe-fbe388cf2c68.png)
![image](https://user-images.githubusercontent.com/11816582/221378113-82ab086c-5eaf-4740-be59-beee0f7326ab.png)

Running the full set of tests on the beta 7 maps now. I will update once complete.

**Comment by 1cosmologist** [comment]
Beta 7 brings models much closer to the observations:
![image](https://user-images.githubusercontent.com/11816582/221380627-cd59ff93-92d6-44d7-ae7d-45656fabcdff.png)
![image](https://user-images.githubusercontent.com/11816582/221380635-2b651641-9fd4-4e8b-bd73-9b29c9134a29.png)

There is perhaps a small excess of power in the models.
The full results summary for the beta 7 synchrotron maps can be found [here](https://docs.google.com/presentation/d/1fquaXcN6YJEXZQUyxFCstbcbFhtgN_ZOG2DI45EG7Ao/edit?usp=sharing).
The updated Jupyter notebook is available [here](https://github.com/1cosmologist/code_shares/blob/main/pysm3.4.0.b7_validation_clean.ipynb).

**Comment by brandonshensley** [comment]
Excellent news. Thank you for turning this around so quickly @zonca and @1cosmologist!

**Comment by delabrou** [comment]
Hi everyone, we have a traceability problem... we need to have some versioning for the PySM input maps, so that one cannot run the model thinking they use the most up-to-date model while in fact using a previous map stored in the cache... Can this be fixed easily?

**Comment by zonca** [comment]
@delabrou yes, this is a problem that only affects people that have used a beta release. People using stable releases are not affected.
I plan to rename all maps and add a timestamp when I release the stable 3.4.0. So that even if people used a beta release previously, they would not by mistake use an outdated file from the cache.

**Comment by 1cosmologist** [comment]
Further validation of the synchrotron models in the CMB-S4 deep patch:
![image](https://user-images.githubusercontent.com/11816582/221713413-67374a4c-9601-48b9-9f25-29b9be0254dc.png)
![image](https://user-images.githubusercontent.com/11816582/221713429-15f9960d-cfdd-4ade-967a-ffcf997bbb78.png)
Looks pretty good! Slides updated with summary of results for the CMB-S4 patch.

**Comment by zonca** [comment]
thanks @1cosmologist, could you please share the latest version of the notebook? It would be nice to add it to the documentation of PySM

**Comment by 1cosmologist** [comment]
The notebook for the CMB-S4 SAT-TMA common patch analysis can be found [here](https://github.com/1cosmologist/code_shares/blob/main/pysm3.4.0.b7_S4validation_clean.ipynb).

**Comment by zonca** [comment]
this analysis is included in the paper in preparation, no need to add it to the documentation of PySM.
