### ISSUE TITLE
Add a note in the docs about the polarization convention?

### ISSUE THREAD

**Issue by ziotom78** [galsci/pysm#160]
I was looking in the docs to check the polarization convention used by PySM3, but I wasn't able to find it. I assume that it uses the Healpix convention instead of the IAU, as this is what the WMAP and Planck teams have done, but I wanted to be sure.

(See [here](https://healpix.sourceforge.io/html/intro_HEALPix_conventions.htm#SECTION633) and [here](https://lambda.gsfc.nasa.gov/product/about/pol_convention.html), the two conventions differ for the sign of the Stokes parameter U.)

**Comment by zonca** [comment]
yes, sure, we always assume the COSMO convention. Is any project you are working on using IAU instead?

I'll think where to put it within the docs.

**Comment by ziotom78** [comment]
Thanks for the information! We're in the process of deciding which convention to adopt, but first we wanted to do a survey of what is used by the tools we are using in our simulations.

**Comment by ziotom78** [comment]
Sorry, I closed the issue but perhaps you want to keep it open until you update the docs.

**Comment by zonca** [comment]
I suggest using COSMO.
I think in the CMB field everyone always assumes COSMO, it is going to be confusing to use IAU instead.

**Comment by zonca** [comment]
in `healpy` `POLCCONV` is not handled at all.
