### ISSUE TITLE
d6 correlation length

### ISSUE THREAD

**Issue by kmsurrao** [galsci/pysm#171]
Hi, the documentation mentions that the user can specify a correlation length for the d6 model (https://pysm3.readthedocs.io/en/latest/models.html#dust). Where would that correlation length be specified when creating a Sky object containing d6?

**Comment by zonca** [comment]
the model is defined here:
https://github.com/galsci/pysm/blob/main/pysm3/data/presets.cfg#L95-L108

You can check this tutorial on ways to customize a model:
https://pysm3.readthedocs.io/en/latest/customize_components.html
