### ISSUE TITLE
Are there any extra small scales injected beyond \ell~1200 for pysm `d0` and `d1` dust models?

### ISSUE THREAD

**Issue by yaojian95** [galsci/pysm#174]
Hi all, 

I'm using pysm `d0` to generate dust maps to test lensing reconstruction methods, but I found the dust models only have signal for multipoles < 1200. The templates for `d0` are at `nside=512` but originally I thought there are Gaussian small scales injected for arbitrary resolution. So this is not the case?

![image](https://github.com/galsci/pysm/assets/14847517/45bf7029-ccfe-49cd-af66-9680c077d3df)

**Comment by zonca** [comment]
see https://pysm3.readthedocs.io/en/latest/#best-practices-for-model-execution
for PySM 2 models, you should always run PySM at 512 to avoid `ud_grade`.
the only model with on-the-fly small scales is `d11`, all other models just have small scales inside the templates.
So whatever was the small scales generation done at the template level, that is what we get in PySM for all models except `d11`.
