### ISSUE TITLE
Seed for c4 model

### ISSUE THREAD

**Issue by erussier** [galsci/pysm#177]
I would like to generate the CMB tensor modes and consistently add it to the lensed c4 maps that I have already generated. I am wondering which seed was used and how it was set to generate the c4 model in PySM. Could you pinpoint me to how the seed is generated and which one was used?

**Comment by zonca** [comment]
please check the docs https://pysm3.readthedocs.io/en/latest/websky.html#primary-and-lensed-cmb
and check also the documentation about websky.
If this still doesn't answer your question, please be more specific and I'll try to help.

**Comment by zonca** [comment]
@erussier please reopen if issue was not solved.
