### ISSUE TITLE
web sky issue in tsz simulations

### ISSUE THREAD

**Issue by Debabrataadak** [galsci/pysm#182]
File "/anaconda3/lib/python3.7/site-packages/pysm3/sky.py", line 179, in get_emission
    output += comp.get_emission(freq, weights=weights)
  File "/.local/lib/python3.7/site-packages/astropy/units/decorators.py", line 253, in wrapper
    return_ = wrapped_function(*func_args, **func_kwargs)
  File "/anaconda3/lib/python3.7/site-packages/pysm3/models/websky.py", line 264, in get_emission
    get_sz_emission_numba(freqs, weights, self.m.value, is_thermal) << u.uK_RJ
TypeError: expected dtype object, got 'numpy.dtype[float32]'

**Comment by Debabrataadak** [comment]
thanks..yes problem resolved for tsz.

However, none of the co's can generate non-zero maps. Values at all pixels are all zero.

**Comment by zonca** [comment]
CO are line emissions, you need to specify the exact line frequency up to whatever decimals are in the code.

**Comment by Debabrataadak** [comment]
Can we simulate multiple realisations of CIB and SZ? I do not find to set seed of the realisation in these classes.

**Comment by zonca** [comment]
No

**Comment by zonca** [comment]
Please provide minimal runnable code that produces this error.

**Comment by Debabrataadak** [comment]
sky = pysm3.Sky(nside=512, preset_strings=["cib1"])
map_100GHz_bandpass = sky.get_emission(x[1:]*u.GHz, y[1:])

x and y contains bandpass frequencies and corresponding bandpass response.
map_100GHz_bandpass
<Quantity [[0., 0., 0., ..., 0., 0., 0.],
[0., 0., 0., ..., 0., 0., 0.],
[0., 0., 0., ..., 0., 0., 0.]] uK_RJ>

**Comment by zonca** [comment]
How do I test without them?
Please prepare the simplest x and y that show the problem and share an entirely runnable code I can paste and execute.

**Comment by zonca** [comment]
2 weeks without follow-up, closing. Please open another issue with a runnable code snippet if still need help
