### ISSUE TITLE
Fix WCS issue in CAR maps

### ISSUE THREAD

**Issue by zonca** [galsci/pysm#192]
the PySM function `apply_smoothing_and_coord_transform` supports CAR outputs, however, there was a bug due to `astropy.units.Quantity` stripping away the WCS, then some default WCS was attached in the map writing process but this was the wrong WCS.

See https://gist.github.com/zonca/278a243f19bbb59cd55a9f42f6348575

@msyriac the WCS which I think is the right one is:

    car:{cdelt:[-1,1],crval:[0.5,0],crpix:[180.50,90.50]}

can you confirm this is fine?

I create it here:

https://github.com/zonca/pysm/blob/9e6090d23db71ce4b0de36595e7885e1416dc585/src/pysm3/utils/spherical_harmonics.py#L116-L119

**Comment by zonca** [comment]
better use nbviewer: https://nbviewer.org/gist/zonca/278a243f19bbb59cd55a9f42f6348575

**Comment by msyriac** [comment]
Yes, that WCS makes more sense.  Which function wrote the default WCS? If it is a pixell function, we should fix it.

**Comment by zonca** [comment]
this was fixed in 58645c2a45585cbf27a34f869b84dc35b2e87fbe
