### ISSUE TITLE
Including CO molecular emission

### ISSUE THREAD

**Issue by giuspugl** [galsci/pysm#64]
It would be great if we can include this emission into pysm, similarly to what we've done in https://github.com/simonsobs/so_pysm_models/blob/master/so_pysm_models/co_lines.py

@zonca  do you think that the interface changed that much ?

**Comment by zonca** [comment]
Yes, I'll import all components into PySM3 and then discontinue so_pysm_models

**Comment by giuspugl** [comment]
sounds great! thanks a lot!

**Comment by zonca** [comment]
see https://github.com/galsci/pysm/pull/86
