### ISSUE TITLE
Dust spectral index and temperature based on GNILC

### ISSUE THREAD

**Issue by zonca** [galsci/pysm#69]
See comparison between GNILC and PySM 2 here:
https://nbviewer.jupyter.org/gist/zonca/c6aa3e83f0151666e33a28cc84c0ba20

Suggestion by Hans Kristian (referring to the PySM 2 templates) was: 

> 1) threshold beta_dust between 1.4 and 1.7, and smooth to ~2 degrees
FWHM, to suppress the worst CO, point source and CIB effects
> 2) Smooth T_dust also to ~2 degrees, to reduce the worst Planck noise
sensitivity

However no idea how to proceed. @brandonshensley @NicolettaK?

**Comment by NicolettaK** [comment]
Hi @zonca. 
I have the new templates for thermal dust beta and temperature that we are currently using for LiteBIRD. 
They are obtained by smoothing the Commander maps at 2°. No need to reduce the beta range as it is already ok after smoothing. Shall I share them with you?

**Comment by zonca** [comment]
no @NicolettaK thanks, I think it would be better to use the GNILC products for templates / spectral indices / dust temperature

**Comment by giuspugl** [comment]
I've finalized a procedure to inject smaller angular scales to the spectral parameters.
- we use the Planck GNILC maps of Bd and Td. 
-  fit a power law in the range $\ell \in [100,400]$ which corresponds to the range we fit the Intensity GNILC 2015 map 
- for the whole analysis we evaluate fullsky power spectra with `ANAFAST` 
- Modulate by total intensity map  both Bd and Td (?) 
 
![image](https://user-images.githubusercontent.com/8957029/136187469-02f84f7f-2952-48e7-bf25-059b8b8c606f.png)
![image](https://user-images.githubusercontent.com/8957029/136187494-ca55faa8-106b-439c-aa6b-3719d12eec79.png)

![image](https://user-images.githubusercontent.com/8957029/136187676-1e809adb-c7a3-4ae1-bc8b-2b9743dfb233.png)

**Comment by zonca** [comment]
@giuspugl the notebook for spectral index and T dust is at https://github.com/galsci/pysm/blob/f3b79810d22805cf5b0904eb13f65df6c6b6dbed/docs/preprocess-templates/gnilc_dust_spectral_index_T_dust.ipynb
Do you have an executed version of that notebook for reference? (in a gist)
I checked in this Gist (https://gist.github.com/giuspugl/d36a0e529a3b4a89c19bce5b58c9494a) but the cells related to spectral index and T_dust are not executed.

Instead of recomputing the modulation factor in that notebook, can I load the modulation map for T that I have created in the notebook which creates the templates? Or do they differ somehow?

**Comment by giuspugl** [comment]
Sorry about that ! Here you can find an updated notebook 
https://gist.github.com/giuspugl/d36a0e529a3b4a89c19bce5b58c9494a
i made sure it is compiled also for the spectral parameters too . 

> Instead of recomputing the modulation factor in that notebook, can I load the modulation map for T that I have created in the notebook which creates the templates? Or do they differ somehow?
Yes! the modulation for Td and Beta_dust is the same as the  intensity one.

**Comment by zonca** [comment]
What do you think about the reusing the same modulation map?

**Comment by brandonshensley** [comment]
> What do you think about the reusing the same modulation map?

Reusing the modulation map seems fine to me as long as the fluctuations themselves are different. Physically it is sensible for the amplitude of fluctuations to be related to the total intensity.

**Comment by zonca** [comment]
Implemented in https://github.com/galsci/pysm/pull/104

**Comment by zonca** [comment]
implemented in #108
