### ISSUE TITLE
GNILC dust model with stochastic small scales and variable specral index d11

### ISSUE THREAD

**Issue by zonca** [galsci/pysm#84]
Based on `d10`

`d11` will have templates just at large scale saved at low nside, C_ell of small scales and map of modulation at low nside loaded from network.
`synalm` + `almxfl` + `alm2map` to generate templates on the fly.
Using a specific seed should reproduce `d10` but on the fly.
If seed is not specified, the small scales are stochastic.

**Comment by zonca** [comment]
@giuspugl @seclark @bthorne93 @brandonshensley any feedback?

**Comment by brandonshensley** [comment]
This sounds great. Though I am not sure why we need to store the high nside maps for d9 at all? Just to save on computation time for when you don't need many realizations?

**Comment by seclark** [comment]
Let's be sure to include positive TE in the small-scale C_ell

**Comment by zonca** [comment]
> This sounds great. Though I am not sure why we need to store the high nside maps for d9 at all? Just to save on computation time for when you don't need many realizations?

correct, anyway the maps are only cached by the user if needed, so it is not a big issue.

**Comment by zonca** [comment]
> Let's be sure to include positive TE in the small-scale C_ell

so, based on the notebook at: https://nbviewer.jupyter.org/gist/zonca/79f202f1d7decb59767e70fdcb46f5d6
We save just TEB in logpoltens formalism. Then when we transform back from logpoltens to IQU, we should get some TE.
Do you think we should double-check that the TE we get is positive?
I added TE comparison at the end between input and outputs:

![image](https://user-images.githubusercontent.com/383090/133725710-c2a8a5a8-6027-4bc7-97d8-1298f10adba5.png)

**Comment by zonca** [comment]
I have done a test where I reproduce the `d9` model by using the same seed, the input maps,cl,alms used here are available at https://portal.nersc.gov/project/cmb/pysm-data/gnilc/:

https://gist.github.com/fa6e78df72230028ac027cf0e338aa74

The plan is that this model can be generated directly at any NSIDE.

I don't want to create too many models, so my proposal is:

* `d9` with templates at 1024 and 8192, fixed T_d and spectral index
* `d10` same templates, but variable T_d and spectral index
* `d11` like `d10`, but stochastic (it reproduces `d10` for specified seed)

**Comment by brandonshensley** [comment]
> Is it possible to generate dust + syn with different realizations using the recent release?

Hi @cfenguiuc, it is now! See [this issue](https://github.com/galsci/pysm/issues/112).

**Comment by cfenguiuc** [comment]
That is awesome!!

Sincerely,

Prof. Chang Feng
Department of Astronomy
University of Science and Technology of China
