### ISSUE TITLE
GNILC dust model with variable spectral index and dust temperature d10

### ISSUE THREAD

**Issue by zonca** [galsci/pysm#85]
Having variable spectral parameters are of course one of the challenges for many foreground cleaning methodologies. personally, I am in favor of having another model with spatially variable beta and T_d ,   e.g. the ones from GNILC maps (see [Planck 2016](https://www.aanda.org/articles/aa/full_html/2016/12/aa29022-16/aa29022-16.html) ).

_Originally posted by @giuspugl in https://github.com/galsci/pysm/issues/83#issuecomment-921606841_

**Comment by zonca** [comment]
@giuspugl @seclark @brandonshensley this could be `d11`, we need a volunteer to prepare these 2 maps, possibly adding small scales as well.

**Comment by giuspugl** [comment]
this might  be interesting!  do you mean to  inject small scales into the maps of beta and T_d ? that's gonna be totally different approach wrt LogPol tens. formalism ..

**Comment by brandonshensley** [comment]
Yes, sorry, was thinking about the d0 model when I gave values for beta and Td. We do absolutely need spatially variable beta and Td maps, ideally with small scales added in a way similar to how the I maps are handled currently. For simulation purposes, I don't think anything simpler than this proposed d11 is realistic.

**Comment by giuspugl** [comment]
I will  prepare a notebook that 'll combine all the maps for this new `d11`  model.

**Comment by zonca** [comment]
> Yes, sorry, was thinking about the d0 model when I gave values for beta and Td. We do absolutely need spatially variable beta and Td maps, ideally with small scales added in a way similar to how the I maps are handled currently. For simulation purposes, I don't think anything simpler than this proposed d11 is realistic.

@brandonshensley I'd rather also keep `d9` with uniform spectral index, so we have an equivalent of `d0`. However if you think it is more harmful than useful, we can use variable index in both `d9` and `d10`.

**Comment by zonca** [comment]
> I will prepare a notebook that 'll combine all the maps for this new `d11` model.

thanks @giuspugl, please just do spectral index and T_d copying functions from the other notebook. don't do all together.

**Comment by brandonshensley** [comment]
> > Yes, sorry, was thinking about the d0 model when I gave values for beta and Td. We do absolutely need spatially variable beta and Td maps, ideally with small scales added in a way similar to how the I maps are handled currently. For simulation purposes, I don't think anything simpler than this proposed d11 is realistic.
> 
> @brandonshensley I'd rather also keep `d9` with uniform spectral index, so we have an equivalent of `d0`. However if you think it is more harmful than useful, we can use variable index in both `d9` and `d10`.

That sounds fine to present them as an updated `d0`.

**Comment by giuspugl** [comment]
I have looked into the GNILC spectral parameters maps released in 
http://pla.esac.esa.int/pla/aio/product-action?MAP.MAP_ID=COM_CompMap_Dust-GNILC-Model-Spectral-Index_2048_R2.00.fits 
and 
http://pla.esac.esa.int/pla/aio/product-action?MAP.MAP_ID=COM_CompMap_Dust-GNILC-Model-Spectral-Index_2048_R2.00.fits 

The major concern is that the sub-degree scales in those maps are present and it is hard to see the effects you can see from the power spectra : 
![image](https://user-images.githubusercontent.com/8957029/134037616-47676d03-e7d8-4e6d-ade2-689594a3b761.png)

I'd propose to filter out all the small scales above `ell>100` so that we are sure not to inject artefacts post -component separation . What do you think ?

**Comment by brandonshensley** [comment]
Thanks Giuseppe, this is a nice analysis. I like that plan a lot.

**Comment by zonca** [comment]
Renamed to `d10` so we go in order of complexity

**Comment by zonca** [comment]
@giuspugl can you please continue the work on spectral index and dust temperature from GNILC in https://github.com/galsci/pysm/issues/69?
