### ISSUE TITLE
Synchrotron spectral index corrected with SPASS

### ISSUE THREAD

**Issue by zonca** [galsci/pysm#96]
@NicolettaK has an updated version of the [notebook](https://gist.github.com/NicolettaK/f801f299a7de116651758ea286eaed66) to generate synchrotron beta maps (apologies Nico if you've already posted this elsewhere!). A standalone implementation (i.e., with various parameters hard coded) begins in Cell 31. @giuspugl does this have everything you need to make an implementation that parallels yours for dust beta?

_Originally posted by @brandonshensley in https://github.com/galsci/pysm/issues/73#issuecomment-964472151_

**Comment by zonca** [comment]
@NicolettaK are SPASS_beta_fwhm2_ns256.fits and cl_fit_spass.fits publicly available?

**Comment by giuspugl** [comment]
I think we're ready to finalize synchrotron too.  However we have just a small tweak to agree on : 


We do observe a similar behaviour in the power law fitted for syncrotron as shown in the power spectra of log pol tens quantities below, i.e. a flatter spectral index for EE and BB than in TT 
![image](https://user-images.githubusercontent.com/8957029/141129644-675a777a-8f9f-44ef-8f61-481f1d8e822f.png)

This indeed results in an unphysical result with EE being larger than TT at `ell>400`. 
![image](https://user-images.githubusercontent.com/8957029/141129830-86fa40f9-92fc-4dec-bba2-5d4b323613b4.png)

I would propose the same approach as for the dust see #97. where we inject small scales in EE and BB with the same power law as in TT.  
How does that sound ?

**Comment by brandonshensley** [comment]
Thanks @giuspugl, I agree completely with your suggestion of using the same spectrum as measured in TT.

**Comment by zonca** [comment]
implemented in #106
